### ISSUE TITLE
Correct version number?

### ISSUE THREAD

**Issue by afragen** [Appsero/client#19]
I noticed the current release is v1.2.1. Is the following variable supposed to reflect that or is it specific to `class Client`?

https://github.com/Appsero/client/blob/d110c537f4ca92ac7f3398eee67cc6bdf506a4fb/src/Client.php#L16

**Comment by tareq1988** [comment]
The variable is supposed to reflect the release, not the `Client` class. Seems like it was missed.

CC: @bdmehedi

**Comment by bdmehedi** [comment]
Yes, it was missed. We will fix this in the next release.
And it doesn't reflect the `Client` class
