### ISSUE TITLE
Make pot failed.

### ISSUE THREAD

**Issue by oberonlai** [Appsero/client#20]
Hi there,

I tried to generate the .pot of appsero client but failed. I was sure that I have use `$client->set_textdomain` method to set my text domain  and used the wp cli make-pot to generate. But the .pot file still can't grab the translated string. Could you help me how to process the .pot file? Thanks for your help.

**Comment by saiftheboss7** [comment]
We'll need to do a release of the Appsero client which is translatable in a future release. Currently, it's not possible to create `.pot` file
