### ISSUE TITLE
Appsero SDK Integration is Not Working

### ISSUE THREAD

**Issue by Chooton838** [Appsero/client#24]
Active a Plugin (Managed with Appsero) -> User Data Collection Consent Pop-Up is functionally not working (Pop-Up reappears for both Allow/ No Thanks action and is not closing)
Appsero Dashboard -> Showing SDK Integration is failed

**Comment by anis3139** [comment]
There is no isssues in appsero end.

**Comment by Chooton838** [comment]
This issue is not Appsero end, it occurred because of file naming convention. (If user uses “SPACE” on file_name then the issue arises)
