### ISSUE TITLE
[Deactivation popup] The Deactivation popup always showing the same reason. 

### ISSUE THREAD

**Issue by YeasinArafat1998** [Appsero/client#26]
**Description:**
The deactivation popup is always showing "Dokan Pro is expensive, and I am upgrading to Dokan Pro." Even if I want to deactivate other plugins such as wePOS, texty, and so on. 

**Video:**
Here is a screencast to help better understand the issue.
https://www.loom.com/share/2ed8d1a4e0ff4c2f9d68037a931c01a2

**Expected Behavior:**
The popup should show the current plugin name.

**Comment by saiftheboss7** [comment]
Not an issue. It happened only on Dokan because of wrong implementation.
