### ISSUE TITLE
Appsero SDK should work on localhost

### ISSUE THREAD

**Issue by saiftheboss7** [Appsero/client#32]
https://www.youtube.com/watch?v=zVo13fZw9gM 

As the video shows, the popup while deactivating a plugin should come even if the plugin is on localhost. In recent release of the SDK, 
- if a plugin is being deactivated, the Appsero deactivation popup doesn't trigger
- If a plugin is being installed for the first time, Appsero opt-in top bar doesn't trigger. We need to fix the functionality. 

(However, on Appsero Helper end, there should be check so that user cannot add localhost site on Appsero Dashboard. This is not related to SDK implementation)

**Comment by anisAronno** [comment]
It's showing as 'done.' This issue may need to be closed.

**Comment by saiftheboss7** [comment]
@anisAronno A short video
